# Generated by Django 4.1 on 2022-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_idx', models.AutoField(primary_key=True, serialize=False)),
                ('survey_idx', models.IntegerField()),
                ('userId', models.CharField(max_length=50, verbose_name='아이디')),
                ('num', models.IntegerField()),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('num4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_idx', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50, verbose_name='아이디')),
                ('question1', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('question2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('question3', models.TextField()),
                ('ans5', models.TextField()),
                ('ans6', models.TextField()),
                ('question4', models.TextField()),
                ('ans7', models.TextField()),
                ('ans8', models.TextField()),
                ('question5', models.TextField()),
                ('ans9', models.TextField()),
                ('ans10', models.TextField()),
                ('status', models.CharField(default='y', max_length=1)),
            ],
        ),
    ]
