# Generated by Django 4.1 on 2022-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[                                                                             # id를 보여준다.                   
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)), #모델에서 만들어진것들이 만들어짐
                ('url', models.URLField(unique=True, verbose_name='url')),
            ],
        ),
    ]
