# Generated by Django 4.1 on 2022-08-25 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('passwd', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('postdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
