# Generated by Django 4.1 on 2022-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewboard',
            fields=[
                ('reviewnum', models.AutoField(primary_key=True, serialize=False, verbose_name='글번호')),
                ('prodnum', models.IntegerField(verbose_name='상품번호')),
                ('reviewdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('userid', models.CharField(max_length=20, verbose_name='작성자')),
                ('reviewtitle', models.CharField(max_length=1000, verbose_name='글제목')),
                ('reviewcontent', models.CharField(max_length=1000, verbose_name='글내용')),
                ('reviewip', models.CharField(max_length=15, verbose_name='아이피')),
            ],
        ),
    ]
