"""
Django settings for MBEx project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

import os
MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR ,"media")


LOGGING = {
    "version" : 1,
    "disable_existing_loggers" : False, # 보이지 않겠냐
    "formatters" : { # 저장된 로그파일의 형식, 딕셔너리로 들어감
        "format1" : {
            "format" : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s", # 시간을 먼저 찍어라, 레벨이름, 이름, 줄번호, 메시지
            "datefmt" : "%Y-%m-%d %H:%M:%S",
            },
        "format2" : {
            "format" : "%(levelname)s %(message)s",
            },
        },
    "handlers" : {
        # 파일로 출력하는 형식
        "file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join( BASE_DIR, "log/logfile.log" ),
            "encoding" : "utf-8",
            "maxBytes" : 1024 * 1024 * 5, # 5메가
            "backupCount" : 5,
            "formatter" : "format1", # 출력 형식을 위에만든 format1로 지정
            },
        "console" : {
            "level" : "DEBUG",
            "class" : "logging.StreamHandler",
            "formatter" : "format2",
            },
        },
    "loggers" : {  # 누가 출력할 것인지
        # 로거의 종류
        "django" : {
            "handlers" : ["console"], # 에러까지 있으면 잘라쓰기 힘듬, 콘솔에만 출력
            "propagate" : True,
            "level" : "WARNING",
            },
        "django.request" : {
            "handlers" : ["console"],
            "propagate" : True,
            "level" : "WARNING",
            },
        "member" : {
            "handlers" : ["file"],
            "propagate" : True,
            "level" : "INFO",
            },
        "board" : {
            "handlers" : ["file"],
            "propagate" : True,
            "level" : "INFO"
            }        
        }    
    
    
    
    }
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^_f9%qmqy75#4v^7odug8(i7*s2xar25j24^c*41j%-l!^gxu!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost","127.0.0.1","192.168.0.118"]


# Application definition

INSTALLED_APPS = [
    'mathfilters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #어플 마다 설정이 다를때 하는거 Config
    "member.apps.MemberConfig", 
    "board.apps.BoardConfig", 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MBEx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MBEx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
