# Generated by Django 4.1 on 2022-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnaBoard',
            fields=[
                ('noticenum', models.AutoField(primary_key=True, serialize=False, verbose_name='공지사항 글번호')),
                ('adminid', models.CharField(max_length=20, verbose_name='작성자')),
                ('noticetitle', models.CharField(max_length=1000, verbose_name='공지사항 글번호')),
                ('content', models.CharField(max_length=6000, verbose_name='글내용')),
                ('restep', models.IntegerField(verbose_name='글순서')),
                ('noticedate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
